apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: kube-test-ns
  labels: 
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: hello-kuber
        image: nginx:1.14.2
        ports:
        - containerPort: 80